#!/bin/bash
#change these
PIA_USER=Username
PIA_PASS=Password
QBITTORRENT_ADDRESS=127.0.0.1:8080
QBT_USER=admin
QBT_PASS=adminadmin
#
#optional
DISABLE_IPV6=yes
AUTOCONNECT=false
PREFERRED_REGION=nl_amsterdam
PIA_DNS=true
DIP_TOKEN=no
#
#leave as is
VPN_PROTOCOL=openvpn_udp_strong
PIA_PF=true
#
cd manual-connections
sudo PIA_USER=$PIA_USER PIA_PASS=$PIA_PASS DISABLE_IPV6=$DISABLE_IPV6 QBITTORRENT_ADDRESS=$QBITTORRENT_ADDRESS \
AUTOCONNECT=$AUTOCONNECT PREFERRED_REGION=$PREFERRED_REGION PIA_DNS=$PIA_DNS QBT_USER=$QBT_USER \
DIP_TOKEN=$DIP_TOKEN VPN_PROTOCOL=$VPN_PROTOCOL PIA_PF=$PIA_PF QBT_PASS=$QBT_PASS \
./run_setup.sh